name: gitleaks

on:
  push:
    branches:
      - main
      - pre-release
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run gitleaks
        run: |
          GITLEAKS_VERSION=$(curl -s https://api.github.com/repos/zricethezav/gitleaks/releases/latest |  grep -oP '"tag_name": "\K(.*)(?=")')
          wget https://github.com/zricethezav/gitleaks/releases/download/$GITLEAKS_VERSION/gitleaks\_$GITLEAKS_VERSION\_linux\_x64.tar.gz
          sudo mv gitleaks_$GITLEAKS_VERSION_linux_x64.tar.gz /usr/bin/gitleaks
          tar -xvzf gitleaks_$GITLEAKS_VERSION_linux_x64.tar.gz
          chmod +x /usr/bin/gitleaks
          gitleaks -v --path . --no-git
        shell: bash
