name: gitleaks

on:
  push:
    branches:
      - main
      - pre-release
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run gitleaks
        run: |
          GITLEAKS_VERSION=$(curl -s https://api.github.com/repos/zricethezav/gitleaks/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | sed 's/v//g')
          wget https://github.com/zricethezav/gitleaks/releases/download/v$GITLEAKS_VERSION/gitleaks\_$GITLEAKS_VERSION\_linux\_x64.tar.gz
          sudo mv gitleaks\_$GITLEAKS_VERSION\_linux_x64.tar.gz /usr/bin/gitleaks
          sudo tar -xf /usr/bin/gitleaks/gitleaks\_$GITLEAKS_VERSION\_linux_x64.tar.gz --directory /usr/bin/gitleaks
          chmod +x /usr/bin/gitleaks/gitleaks
          /usr/bin/gitleaks/gitleaks -v --path . --no-git
        shell: bash
